<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.onap.sdc.zusammen.plugin</groupId>
        <artifactId>amdocs-zusammen-search-index</artifactId>
        <version>1.0.5-SNAPSHOT</version>
    </parent>

    <artifactId>zusammen-search-index-empty-plugin</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.onap.sdc.zusammen</groupId>
            <artifactId>zusammen-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.onap.sdc.zusammen</groupId>
            <artifactId>zusammen-datatypes</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.onap.sdc.zusammen</groupId>
            <artifactId>zusammen-commons-health</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>